import { Camera, Sun, Wifi, Shield, Smartphone, Eye, Volume2, HardDrive, Battery, Network, Zap, Server, Cable, Radio, Users, Signal, Car, Lock, Ruler, Router, Globe, Factory, Home, Headphones, Clock, FileText, Mail, UserCheck, Activity, Monitor, Cpu, MemoryStick, Lightbulb, Palette, Navigation, Sparkles, BellRing, ScanEye, Video, Mic } from "lucide-react";
import { Product } from "./ProductCard";

export const products: Product[] = [
  {
    id: "tp-tapo-c660-kit",
    name: "TP-Link Tapo C660 Solar-Powered Pan/Tilt Security Camera Kit",
    sku: "TP-TAPO-C660-KIT",
    price: 2999,
    image: "/lovable-uploads/tapo-c660-product.png",
    boxImage: "/lovable-uploads/tapo-c660-box.png",
    description: "The Tapo C660 delivers 4K 8MP ultra-clear video with 18× digital zoom and full 360° pan/tilt coverage, ensuring no detail is missed. Built-in AI smart detection accurately identifies people, pets, and vehicles, reducing false alerts.",
    features: [
      { icon: Camera, text: "4K 8MP Video" },
      { icon: Eye, text: "360° Pan/Tilt" },
      { icon: Sun, text: "Solar Powered" },
      { icon: Shield, text: "AI Detection" },
      { icon: Wifi, text: "Dual-Band Wi-Fi" },
      { icon: Smartphone, text: "App Control" },
    ],
    highlights: [
      "18× digital zoom for detailed monitoring",
      "Starlight color night vision with F1.6 lens",
      "Built-in spotlights for vivid low-light imaging",
      "Maintenance-free solar power for off-grid locations",
      "Free Person/Pet/Vehicle detection",
      "Privacy mode & encrypted local storage",
    ],
    category: "Security Cameras",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 24,
  },
  {
    id: "tp-tapo-c460-kit",
    name: "TP-Link Tapo 4K 8MP Solar Security Camera Kit | C460",
    sku: "TP-TAPO-C460-KIT",
    manufacturerSku: "Tapo C460 KIT",
    price: 2699,
    image: "/lovable-uploads/tapo-c460-product.png",
    boxImage: "/lovable-uploads/tapo-c460-mounted.png",
    description: "The TP-Link Tapo C460 is a 4K 8MP solar-powered security camera kit designed for outdoor surveillance. It provides ultra-high-definition video and includes a solar panel and high-capacity battery for continuous, maintenance-free operation.",
    features: [
      { icon: Camera, text: "4K 8MP Video" },
      { icon: Sun, text: "Solar Panel" },
      { icon: Battery, text: "High-Capacity Battery" },
      { icon: Shield, text: "Motion Detection" },
      { icon: Volume2, text: "Two-Way Audio" },
      { icon: HardDrive, text: "Local/Cloud Storage" },
    ],
    highlights: [
      "Full-colour night vision day and night",
      "Intelligent motion detection for people, vehicles and pets",
      "Two-way audio communication",
      "Smart notifications to your device",
      "Local or cloud storage options",
      "Tapo app for remote viewing and control",
    ],
    category: "Security Cameras",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 18,
  },
  {
    id: "gs-gwn7806pl-pro",
    name: "Grandstream Enterprise L2++ 48 Port Managed GbE PoE Switch 120W",
    sku: "GS-GWN7806PL-PRO",
    manufacturerSku: "GWN7806PL-PRO",
    price: 9999,
    image: "/lovable-uploads/gwn7806pl-pro-front.png",
    boxImage: "/lovable-uploads/gwn7806pl-pro-back.png",
    description: "Layer 2++ Managed Network switch with 48x Gigabit RJ45 PoE ports and 120W PoE budget. Enterprise-grade networking solution with advanced management features, VLAN support, and seamless integration with Grandstream's GWN Cloud management platform.",
    features: [
      { icon: Network, text: "48 GbE Ports" },
      { icon: Zap, text: "120W PoE Budget" },
      { icon: Server, text: "Layer 2++ Managed" },
      { icon: Shield, text: "Enterprise Security" },
      { icon: Cable, text: "SFP+ Uplinks" },
      { icon: Wifi, text: "Cloud Management" },
    ],
    highlights: [
      "48x Gigabit RJ45 PoE ports for high-density deployments",
      "120W total PoE power budget",
      "Layer 2++ switching with advanced VLAN support",
      "GWN Cloud management platform integration",
      "Enterprise-grade QoS and traffic management",
      "Rack-mountable 1U form factor",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 8,
  },
  {
    id: "gs-gwn7806ph-pro",
    name: "Grandstream Enterprise L2++ 48 Port Managed GbE PoE Switch High-Power",
    sku: "GS-GWN7806PH-PRO",
    manufacturerSku: "GWN7806PH-PRO",
    price: 12999,
    image: "/lovable-uploads/gwn7806ph-pro-front.png",
    boxImage: "/lovable-uploads/gwn7806ph-pro-angle.png",
    description: "Layer 2++ Managed Network switch with 48x Gigabit RJ45 PoE ports. High-power enterprise-grade networking solution with advanced management features, VLAN support, and seamless integration with Grandstream's GWN Cloud management platform. Ideal for high-density PoE deployments.",
    features: [
      { icon: Network, text: "48 GbE Ports" },
      { icon: Zap, text: "High-Power PoE" },
      { icon: Server, text: "Layer 2++ Managed" },
      { icon: Shield, text: "Enterprise Security" },
      { icon: Cable, text: "SFP+ Uplinks" },
      { icon: Wifi, text: "Cloud Management" },
    ],
    highlights: [
      "48x Gigabit RJ45 PoE ports for high-density deployments",
      "High-power PoE budget for demanding devices",
      "Layer 2++ switching with advanced VLAN support",
      "GWN Cloud management platform integration",
      "Enterprise-grade QoS and traffic management",
      "Rack-mountable 1U form factor",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 5,
  },
  {
    id: "gs-gwn7816p",
    name: "Grandstream Enterprise L3 48 Port Managed GbE PoE++ Switch 900W",
    sku: "GS-GWN7816P",
    manufacturerSku: "GWN7816P",
    price: 15499,
    image: "/lovable-uploads/gwn7816p-angle1.png",
    boxImage: "/lovable-uploads/gwn7816p-angle2.png",
    description: "High-capacity Layer 3 managed switch built for enterprise networks requiring advanced performance, scalability, and security. With 48 Gigabit Ethernet ports and 6 10-Gigabit SFP+ uplinks, it delivers robust connectivity for high-density deployments. PoE, PoE+, and PoE++ support with a 900W power budget ensures reliable power delivery to demanding devices.",
    features: [
      { icon: Network, text: "48 GbE + 6 SFP+" },
      { icon: Zap, text: "900W PoE++" },
      { icon: Server, text: "Layer 3 Managed" },
      { icon: Shield, text: "Advanced Security" },
      { icon: Cable, text: "10G Uplinks" },
      { icon: Wifi, text: "Stacking Support" },
    ],
    highlights: [
      "48× Gigabit Ethernet ports + 6× 10-Gigabit SFP+ uplinks",
      "900W PoE budget with PoE/PoE+/PoE++ and dynamic allocation",
      "Full IPv4 and IPv6 protocol support",
      "Stacking support for managing multiple switches",
      "ARP Inspection, IP Source Guard, DHCP snooping security",
      "Dual boot, link aggregation, and storm control",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.8,
    reviewCount: 6,
  },
  {
    id: "gs-gwn7672",
    name: "Grandstream Enterprise WiFi 7 Indoor Access Point | GWN7672",
    sku: "GS-GWN7672",
    manufacturerSku: "GWN7672",
    price: 3999,
    image: "/lovable-uploads/gwn7672-front.png",
    boxImage: "/lovable-uploads/gwn7672-back.png",
    description: "Enterprise-grade Wi-Fi 7 access point designed for medium to high-density environments such as offices, schools, hotels, and large retail spaces. Supports ultra-high-speed wireless connectivity with up to 11Gbps aggregate throughput for demanding applications including HD video streaming, real-time collaboration, and VoIP.",
    features: [
      { icon: Wifi, text: "WiFi 7 BE11000" },
      { icon: Signal, text: "11Gbps Speed" },
      { icon: Users, text: "384 Clients" },
      { icon: Radio, text: "175m Range" },
      { icon: Shield, text: "Secure Boot" },
      { icon: Server, text: "Embedded Controller" },
    ],
    highlights: [
      "Up to 11Gbps aggregate wireless throughput (BE11000)",
      "5Gbps aggregate wired throughput",
      "2x2x2:2 MIMO with MLO, 4KQAM, MRU technology",
      "Coverage range up to 175 metres",
      "Supports up to 384 concurrent Wi-Fi clients",
      "Self-power adaptation with PoE+ auto-detection",
    ],
    category: "Wi-Fi",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.9,
    reviewCount: 15,
  },
  {
    id: "gs-gwn7670",
    name: "Grandstream Enterprise WiFi 7 Indoor Access Point | GWN7670",
    sku: "GS-GWN7670",
    manufacturerSku: "GWN7670",
    price: 2499,
    image: "/lovable-uploads/gwn7670-front.png",
    boxImage: "/lovable-uploads/gwn7670-angle.png",
    description: "Enterprise-grade indoor Wi-Fi 7 Access Point designed for small to medium businesses requiring high-performance wireless connectivity. Delivers multi-gigabit speeds and reliable coverage using 2x2:2 MU-MIMO technology and 4096 QAM modulation. Controller-less architecture integrates with GDMS and GWN Manager platforms.",
    features: [
      { icon: Wifi, text: "WiFi 7 MU-MIMO" },
      { icon: Signal, text: "4096 QAM" },
      { icon: Users, text: "256 Clients" },
      { icon: Network, text: "2× 2.5GbE PoE+" },
      { icon: Shield, text: "Secure Boot" },
      { icon: Server, text: "Controller-less" },
    ],
    highlights: [
      "Wi-Fi 7 with 2x2:2 MU-MIMO and 4096 QAM",
      "DL/UL OFDMA for improved spectrum efficiency",
      "2× 2.5GbE ports with PoE+ support",
      "Supports up to 256 concurrent clients",
      "Optimised for voice-over-Wi-Fi applications",
      "Compatible with GDMS and GWN Manager",
    ],
    category: "Wi-Fi",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.8,
    reviewCount: 22,
  },
  {
    id: "zk-bg1145l",
    name: "ZKTeco 90-Degree Left Folding Barrier Boomgate 3.5m",
    sku: "ZK-BG1145-L",
    manufacturerSku: "BG1145-L",
    price: 21999,
    image: "/lovable-uploads/zkteco-boomgate.png",
    description: "Professional 90-degree left folding barrier boom gate with 3.5m boom arm. Ideal for parking lots, commercial buildings, and access control points. Features smooth operation, durable construction, and reliable motor system for high-traffic environments.",
    features: [
      { icon: Ruler, text: "3.5m Boom Arm" },
      { icon: Lock, text: "Access Control" },
      { icon: Car, text: "Vehicle Barrier" },
      { icon: Shield, text: "Heavy Duty" },
      { icon: Zap, text: "Fast Operation" },
      { icon: Server, text: "Motor Control" },
    ],
    highlights: [
      "90-degree left folding design for space efficiency",
      "3.5m boom arm length for standard lane widths",
      "Heavy-duty motor for continuous operation",
      "Anti-collision detection system",
      "Manual release for emergency situations",
      "Compatible with access control systems",
    ],
    category: "Access Control",
    brand: "ZKTeco",
    warranty: "1 Year",
    inStock: true,
    rating: 4.4,
    reviewCount: 7,
  },
  {
    id: "ttk-rut260",
    name: "Teltonika Industrial LTE CAT 6 Router | RUT260",
    sku: "TTK-RUT260",
    manufacturerSku: "RUT260",
    price: 3799,
    image: "/lovable-uploads/rut260-front.png",
    boxImage: "/lovable-uploads/rut260-back.png",
    description: "Versatile and compact 4G LTE Wi-Fi router designed for industrial, IoT, and M2M communications. Known for reliability and advanced features, suitable for industrial automation, remote monitoring, retail POS systems, and transportation connectivity.",
    features: [
      { icon: Globe, text: "4G LTE CAT 6" },
      { icon: Wifi, text: "Wi-Fi Access Point" },
      { icon: Factory, text: "Industrial Grade" },
      { icon: Shield, text: "Secure VPN" },
      { icon: Router, text: "Dual SIM" },
      { icon: Network, text: "Ethernet Ports" },
    ],
    highlights: [
      "4G LTE CAT 6 with up to 300 Mbps download speeds",
      "Industrial-grade design for harsh environments",
      "Dual SIM for network failover and load balancing",
      "Built-in Wi-Fi access point for local connectivity",
      "Advanced VPN support for secure remote access",
      "RMS remote management platform compatible",
    ],
    category: "Networking",
    brand: "Teltonika",
    warranty: "2 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 14,
  },
  {
    id: "tp-decobe65-3p",
    name: "TP-Link Deco Wi-Fi 7 Mesh System (3-Pack) | Deco BE65",
    sku: "TP-DECOBE65-3P",
    manufacturerSku: "Deco BE65(3-pack)",
    price: 12999,
    image: "/lovable-uploads/deco-be65-3pack.png",
    boxImage: "/lovable-uploads/deco-be65-back.png",
    description: "Whole-home Wi-Fi 7 mesh system with tri-band capabilities achieving speeds up to 11 Gbps. Features 6 GHz, 5 GHz, and 2.4 GHz bands with Multi-Link Operation (MLO) and 320 MHz channels for ultra-fast, low-latency connectivity supporting 200+ devices.",
    features: [
      { icon: Wifi, text: "WiFi 7 Tri-Band" },
      { icon: Signal, text: "11 Gbps Speed" },
      { icon: Home, text: "Whole-Home Mesh" },
      { icon: Users, text: "200+ Devices" },
      { icon: Network, text: "4× 2.5GbE Ports" },
      { icon: Shield, text: "HomeShield Security" },
    ],
    highlights: [
      "Tri-band WiFi 7 with 6 GHz, 5 GHz, and 2.4 GHz",
      "Up to 11 Gbps aggregate wireless throughput",
      "Four 2.5 Gbps ports per unit for wired backhaul",
      "Multi-Link Operation (MLO) for low latency",
      "320 MHz channels on 6 GHz band",
      "TP-Link HomeShield advanced security",
    ],
    category: "Wi-Fi",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.8,
    reviewCount: 11,
  },
  {
    id: "sy-basic-15",
    name: "Basic Remote Support | Up to 15 Users",
    sku: "SY-BASIC-15",
    price: 5000,
    image: "/lovable-uploads/premium-support-25-50.png",
    description: "Essential remote IT support for small teams up to 15 users. Includes email and WhatsApp support, remote desktop assistance, software troubleshooting, and basic network support during business hours. Ideal for startups and small businesses getting started with managed IT.",
    features: [
      { icon: Mail, text: "Email & WhatsApp" },
      { icon: Headphones, text: "Remote Assistance" },
      { icon: Clock, text: "Business Hours" },
      { icon: Server, text: "Basic Network" },
      { icon: Shield, text: "Software Support" },
      { icon: FileText, text: "4 Hours/Month" },
    ],
    highlights: [
      "Email and WhatsApp support channels",
      "Remote desktop assistance for quick fixes",
      "Software troubleshooting and updates",
      "Printer and basic network support",
      "4 support hours included per month",
      "8am – 5pm business hours coverage",
      "24-hour response SLA",
      "Final price based on custom quote",
    ],
    category: "Support Packages",
    brand: "Siyakha",
    warranty: "Monthly Subscription",
    inStock: true,
    rating: 4.6,
    reviewCount: 28,
  },
  {
    id: "sy-standard-25",
    name: "Standard Support Package | 15–25 Users",
    sku: "SY-STANDARD-25",
    price: 12000,
    image: "/lovable-uploads/premium-support-25-50.png",
    description: "Comprehensive IT support for growing teams of 15–25 users. Includes everything in Basic plus unlimited remote requests, server and cloud support, backup monitoring, antivirus management, and monthly system health checks. Extended support hours for business continuity.",
    features: [
      { icon: Headphones, text: "Unlimited Remote" },
      { icon: Server, text: "Server & Cloud" },
      { icon: HardDrive, text: "Backup Monitoring" },
      { icon: Shield, text: "Antivirus Mgmt" },
      { icon: Activity, text: "Health Checks" },
      { icon: Clock, text: "Extended Hours" },
    ],
    highlights: [
      "Everything included in Basic package",
      "Unlimited remote support requests",
      "Server and cloud infrastructure support",
      "Automated backup monitoring and alerts",
      "Antivirus and endpoint management",
      "Monthly system health check reports",
      "8am – 6pm extended support hours",
      "8-hour response SLA",
      "Final price based on custom quote",
    ],
    category: "Support Packages",
    brand: "Siyakha",
    warranty: "Monthly Subscription",
    inStock: true,
    rating: 4.7,
    reviewCount: 41,
  },
  {
    id: "sy-enterprise-plus",
    name: "Enterprise++ | Custom Solution",
    sku: "SY-ENTERPRISE-PLUS",
    price: 35000,
    image: "/lovable-uploads/premium-support-25-50.png",
    description: "Fully customised enterprise IT solution for organisations with complex requirements. Includes everything in Enterprise plus dedicated team, custom SLAs, strategic IT consulting, compliance management, and bespoke service agreements. Tailored to your exact business needs.",
    features: [
      { icon: Users, text: "Dedicated Team" },
      { icon: FileText, text: "Custom SLA" },
      { icon: Activity, text: "IT Consulting" },
      { icon: Shield, text: "Compliance" },
      { icon: Server, text: "Full Management" },
      { icon: Zap, text: "Priority Everything" },
    ],
    highlights: [
      "Everything in Enterprise package",
      "Dedicated IT team assigned to your account",
      "Fully customisable SLA agreements",
      "Strategic IT consulting and roadmapping",
      "Compliance and audit management",
      "Bespoke service level agreements",
      "Quarterly business reviews",
      "Technology budget planning",
      "Instant priority response",
      "Price quoted based on requirements",
    ],
    category: "Support Packages",
    brand: "Siyakha",
    warranty: "Monthly Subscription",
    inStock: true,
    rating: 5.0,
    reviewCount: 8,
  },
  {
    id: "dell-pro-15-essential",
    name: "Dell Pro 15 Essential 15.6-inch FHD Laptop",
    sku: "DELL-PRO15-ESS",
    manufacturerSku: "Pro 15 Essential",
    price: 12999,
    image: "/lovable-uploads/dell-pro-15-essential.png",
    description: "The Dell Pro 15 Essential is a reliable business laptop featuring a 15.6-inch Full HD display, Intel Core 3 100U processor, 512GB SSD storage, and 8GB RAM. Pre-installed with Windows 11 Pro for enterprise-ready productivity and security features.",
    features: [
      { icon: Monitor, text: "15.6\" FHD Display" },
      { icon: Cpu, text: "Intel Core 3 100U" },
      { icon: HardDrive, text: "512GB SSD" },
      { icon: MemoryStick, text: "8GB RAM" },
      { icon: Shield, text: "Windows 11 Pro" },
      { icon: Battery, text: "Long Battery Life" },
    ],
    highlights: [
      "15.6-inch Full HD (1920×1080) anti-glare display",
      "Intel Core 3 100U processor for efficient performance",
      "512GB M.2 PCIe NVMe SSD for fast boot and load times",
      "8GB DDR4 RAM for smooth multitasking",
      "Windows 11 Pro with enterprise security features",
      "Compact and portable design for professionals",
    ],
    category: "Laptops",
    brand: "Dell",
    warranty: "1 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: "lq-22u-outdoor",
    name: "LinkQNet 22U IP45 Outdoor Vented Wall Mount Cabinet – 611(W) × 675(D)mm",
    sku: "LQ-22U-OUTDOOR",
    manufacturerSku: "22U-IP45-OUTDOOR",
    price: 16192,
    image: "/lovable-uploads/linkqnet-22u-outdoor-cabinet.png",
    description: "Heavy-duty 22U IP45-rated outdoor wall mount cabinet with vented panels for optimal airflow. Designed for harsh environments, this cabinet protects networking and server equipment from dust, rain, and temperature extremes. Ideal for outdoor installations, rooftop deployments, and industrial sites.",
    features: [
      { icon: Server, text: "22U Capacity" },
      { icon: Shield, text: "IP45 Rated" },
      { icon: Lock, text: "Lockable Door" },
      { icon: Factory, text: "Outdoor Rated" },
      { icon: Ruler, text: "611×675mm" },
      { icon: Cable, text: "Cable Management" },
    ],
    highlights: [
      "22U rack space for networking and server equipment",
      "IP45 ingress protection for outdoor environments",
      "Vented panels for passive airflow and cooling",
      "Heavy-duty steel construction with powder coat finish",
      "Lockable front door for equipment security",
      "Wall mount design saves floor space",
    ],
    category: "Cabinets & Racks",
    brand: "LinkQNet",
    warranty: "1 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 6,
  },
  {
    id: "lq-18u-glass",
    name: "LinkQNet 18U 600×800 Cabinet with Glass Door",
    sku: "LQ-18U-GLASS",
    manufacturerSku: "18U-600X800-GLASS",
    price: 6268,
    image: "/lovable-uploads/linkqnet-18u-cabinet-glass.png",
    description: "Professional 18U server cabinet with tempered glass front door for easy equipment monitoring. The 600×800mm footprint provides ample depth for standard networking and server hardware. Features perforated side panels for ventilation and castors for mobility.",
    features: [
      { icon: Server, text: "18U Capacity" },
      { icon: Eye, text: "Glass Door" },
      { icon: Lock, text: "Lockable" },
      { icon: Ruler, text: "600×800mm" },
      { icon: Cable, text: "Cable Access" },
      { icon: Network, text: "Standard 19\"" },
    ],
    highlights: [
      "18U rack capacity in standard 19-inch format",
      "Tempered glass front door for equipment visibility",
      "600mm wide × 800mm deep for standard equipment",
      "Lockable front and rear access for security",
      "Perforated panels for optimal airflow",
      "Castors and levelling feet included",
    ],
    category: "Cabinets & Racks",
    brand: "LinkQNet",
    warranty: "1 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 9,
  },
  {
    id: "lq-9u-corner",
    name: "LinkQNet 9U Wall Box Corner Cabinet 600×600",
    sku: "LQ-9U-CORNER",
    manufacturerSku: "9U-CORNER-600X600",
    price: 3264,
    image: "/lovable-uploads/linkqnet-9u-corner-cabinet.png",
    description: "Compact 9U corner wall mount cabinet designed to fit neatly into room corners, maximising space efficiency. Features a tempered glass front door for equipment visibility, built-in fan for cooling, and perforated side panels. Ideal for small offices, retail stores, and home networks.",
    features: [
      { icon: Server, text: "9U Capacity" },
      { icon: Eye, text: "Glass Door" },
      { icon: Lock, text: "Lockable" },
      { icon: Ruler, text: "600×600mm" },
      { icon: Home, text: "Corner Mount" },
      { icon: Network, text: "Standard 19\"" },
    ],
    highlights: [
      "9U rack space in compact corner-mount design",
      "Tempered glass front door with lock for security",
      "Built-in cooling fan for equipment ventilation",
      "600mm wide × 600mm deep footprint",
      "Perforated side panels for airflow",
      "Wall mount bracket included for easy installation",
    ],
    category: "Cabinets & Racks",
    brand: "LinkQNet",
    warranty: "1 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 11,
  },
  {
    id: "tp-tapo-l530e",
    name: "TP-Link Tapo L530E Smart Wi-Fi Light Bulb – Multicolour",
    sku: "TP-TAPO-L530E",
    manufacturerSku: "Tapo L530E",
    price: 859,
    image: "/lovable-uploads/tapo-l530e-product.png",
    boxImage: "/lovable-uploads/tapo-l530e-box-2pack.png",
    description: "Smart Wi-Fi multicolour light bulb with 16 million hues, 806 lumens brightness, and E27 fitting. Control via the Tapo app, Amazon Alexa, or Google Assistant – no hub required. Available in 1, 2, or 4-pack options. Features scheduling, sunrise/sunset modes, and away mode for security.",
    features: [
      { icon: Palette, text: "16M Colours" },
      { icon: Lightbulb, text: "806 Lumens" },
      { icon: Wifi, text: "Wi-Fi Control" },
      { icon: Smartphone, text: "App Control" },
      { icon: Clock, text: "Schedule & Timer" },
      { icon: Volume2, text: "Voice Control" },
    ],
    highlights: [
      "16,000,000 colour hues with 2500–6500K temperature range",
      "60W equivalent at only 8.3W – energy class F",
      "Works with Amazon Alexa and Google Assistant",
      "No hub required – connects directly to 2.4GHz Wi-Fi",
      "Schedule, timer, sunrise/sunset automation modes",
      "Away mode simulates occupancy for security",
      "Dimmable 1%–100% via Tapo app",
      "25,000-hour lifespan with 15,000 switching cycles",
    ],
    category: "Smart Home",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 32,
  },
  {
    id: "tp-tapo-rv30-max",
    name: "TP-Link Tapo RV30 Max Robot Vacuum & Mop – 5300Pa Suction",
    sku: "TP-TAPO-RV30-MAX",
    manufacturerSku: "Tapo RV30 Max",
    price: 5499,
    image: "/lovable-uploads/tapo-rv30-max-product.png",
    boxImage: "/lovable-uploads/tapo-rv30-max-box.png",
    description: "Ultra-powerful 5300Pa robot vacuum and mop with LiDAR + IMU dual navigation, Tapo IQ+ smart cleaning, mesh grid mopping, carpet avoidance, and 4× multi-floor mapping. Works with Amazon Alexa and Google Assistant for voice control.",
    features: [
      { icon: Zap, text: "5300Pa Suction" },
      { icon: Navigation, text: "LiDAR Navigation" },
      { icon: Sparkles, text: "Tapo IQ+ Smart" },
      { icon: Smartphone, text: "App Control" },
      { icon: Volume2, text: "Voice Control" },
      { icon: Battery, text: "Auto-Charging" },
    ],
    highlights: [
      "Ultra-powerful 5300Pa hyper suction for all floor types",
      "LiDAR + IMU dual navigation – maps your home in minutes",
      "Mesh Grid mopping for comprehensive, thorough cleaning",
      "Carpet avoidance in mopping mode to keep carpets dry",
      "Tapo IQ+ smart cleaning with advanced sensors & algorithms",
      "4× multi-floor maps stored locally for whole-home coverage",
      "Auto-charging – returns to dock and resumes where it left off",
      "Works with Amazon Alexa and Google Assistant",
    ],
    category: "Smart Home",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    id: "tp-tapo-d235",
    name: "TP-Link Tapo D235 5MP Video Doorbell Camera",
    sku: "TP-TAPO-D235",
    manufacturerSku: "Tapo D235",
    price: 2599,
    image: "/lovable-uploads/tapo-d235-product.png",
    boxImage: "/lovable-uploads/tapo-d235-battery.png",
    description: "2K 5MP video doorbell camera with 180° ultra-wide view, full-colour night vision, two-way audio, and smart detection for person, vehicle, pet and package. Powered by 10,000mAh battery (up to 8 months) or 8–24V hardwired. IP66 weatherproof with local and cloud storage options.",
    features: [
      { icon: Camera, text: "2K 5MP Clarity" },
      { icon: ScanEye, text: "180° Ultra-Wide" },
      { icon: Sun, text: "Colour Night Vision" },
      { icon: Volume2, text: "Two-Way Audio" },
      { icon: Battery, text: "8-Month Battery" },
      { icon: BellRing, text: "Quick Response" },
    ],
    highlights: [
      "2K 5MP resolution for crystal-clear detail",
      "180° ultra-wide field of view – head-to-toe coverage",
      "Full-colour night vision with built-in spotlight",
      "Free smart detection: person, vehicle, pet & package alerts",
      "10,000mAh battery lasts up to 8 months or hardwire 8–24V",
      "Two-way audio with premium mic and speakers",
      "IP66 weatherproof – reliable in all conditions",
      "MicroSD (up to 512GB) and Tapo Care cloud storage",
    ],
    category: "Security Cameras",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: "syn-dx517",
    name: "Synology DX517 5-Bay Expansion Unit – Diskless",
    sku: "SYN-DX517",
    manufacturerSku: "DX517",
    price: 11934.20,
    image: "/lovable-uploads/synology-dx517-front.png",
    boxImage: "/lovable-uploads/synology-dx517-diagram.png",
    description: "5-bay expansion unit for Synology DiskStation NAS. Seamlessly expand storage capacity with online volume expansion, hot-swappable drive trays, and synchronised system operation. Sold diskless – add your own 3.5\" or 2.5\" SATA drives.",
    features: [
      { icon: HardDrive, text: "5-Bay Expansion" },
      { icon: Server, text: "Hot-Swappable" },
      { icon: Zap, text: "Online Expansion" },
      { icon: Shield, text: "Backup Solution" },
      { icon: Cable, text: "eSATA Interface" },
      { icon: Activity, text: "Synced Operation" },
    ],
    highlights: [
      "Online volume expansion – add capacity without downtime",
      "Dedicated local backup solution for DiskStation",
      "Hot-swappable drive tray design for easy maintenance",
      "Synchronised system operation with DiskStation",
      "Supports 3.5\" and 2.5\" SATA HDD/SSD",
      "eSATA connectivity to host NAS",
      "LED indicators for status, alert, and eSATA",
      "Dual cooling fans for reliable operation",
    ],
    category: "Networking",
    brand: "Synology",
    warranty: "2 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 8,
  },
  {
    id: "fanvil-ca400",
    name: "Fanvil CA400 All-in-One Wireless Conference Solution",
    sku: "FAN-CA400",
    manufacturerSku: "CA400",
    price: 13798.85,
    image: "/lovable-uploads/fanvil-ca400-kit.png",
    boxImage: "/lovable-uploads/fanvil-ca400-camera.png",
    description: "All-in-one wireless conference solution combining a 4K camera with auto-framing (118.5° wide-angle, 5× digital zoom), speakerphone with 8-array microphone and 3W speaker, and wireless receiver hub. Supports 4K screen-sharing, 1080p wireless video streaming, and BYOD via USB-C.",
    features: [
      { icon: Video, text: "4K Screen Sharing" },
      { icon: Camera, text: "4K Auto-Frame Camera" },
      { icon: Mic, text: "8-Array Microphone" },
      { icon: Wifi, text: "Wireless Streaming" },
      { icon: Monitor, text: "BYOD USB-C" },
      { icon: Volume2, text: "3W Speaker" },
    ],
    highlights: [
      "Wireless 4K screen-sharing for real-time presentations",
      "All-in-one: speakerphone, 4K camera & receiver hub",
      "1080p wireless video streaming – clutter-free setup",
      "8-array mic with AEC, ANS, AGC & vocal enhancement",
      "118.5° wide-angle camera with 5× digital zoom & auto-framing",
      "BYOD support via USB Type-C connection",
      "OSD remote control for camera direction & focal length",
      "Three-step setup – no tangled cables",
    ],
    category: "Collaboration",
    brand: "Fanvil",
    warranty: "2 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 6,
  },
  {
    id: "linkqnet-tpbq34",
    name: "LinkQNet TPBQ34 27,000mAh PD65W Super Quick Charge Powerbank",
    sku: "LQN-TPBQ34",
    manufacturerSku: "TPBQ34",
    price: 1071.70,
    image: "/lovable-uploads/linkqnet-powerbank-front.png",
    boxImage: "/lovable-uploads/linkqnet-powerbank-views.png",
    description: "High-capacity 27,000mAh Li-Polymer powerbank with PD65W super quick charge. Compatible with laptops (PD65W & PD45W), smartphones and tablets. Features a digital indicator for remaining battery level.",
    features: [
      { icon: Battery, text: "27,000mAh Capacity" },
      { icon: Zap, text: "PD65W Quick Charge" },
      { icon: Monitor, text: "Laptop Compatible" },
      { icon: Smartphone, text: "Multi-Device" },
      { icon: Activity, text: "Digital Indicator" },
      { icon: Cable, text: "Li-Polymer Battery" },
    ],
    highlights: [
      "27,000mAh high-capacity Li-Polymer battery",
      "PD65W super quick charge output",
      "Compatible with laptops (PD65W & PD45W)",
      "Digital indicator for remaining battery level",
      "Multiple output ports for simultaneous charging",
      "Compact portable design with carry strap",
    ],
    category: "Networking",
    brand: "LinkQNet",
    warranty: "1 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 12,
  },
];


export const getCategories = (): string[] => {
  return [...new Set(products.map(p => p.category))];
};

export const getBrands = (): string[] => {
  return [...new Set(products.map(p => p.brand))];
};
