import { Camera, Sun, Wifi, Shield, Smartphone, Eye, Volume2, HardDrive, Battery, Network, Zap, Server, Cable, Radio, Users, Signal } from "lucide-react";
import { Product } from "./ProductCard";

export const products: Product[] = [
  {
    id: "tp-tapo-c660-kit",
    name: "TP-Link Tapo C660 Solar-Powered Pan/Tilt Security Camera Kit",
    sku: "TP-TAPO-C660-KIT",
    price: 2875,
    image: "/lovable-uploads/tapo-c660-product.png",
    boxImage: "/lovable-uploads/tapo-c660-box.png",
    description: "The Tapo C660 delivers 4K 8MP ultra-clear video with 18× digital zoom and full 360° pan/tilt coverage, ensuring no detail is missed. Built-in AI smart detection accurately identifies people, pets, and vehicles, reducing false alerts.",
    features: [
      { icon: Camera, text: "4K 8MP Video" },
      { icon: Eye, text: "360° Pan/Tilt" },
      { icon: Sun, text: "Solar Powered" },
      { icon: Shield, text: "AI Detection" },
      { icon: Wifi, text: "Dual-Band Wi-Fi" },
      { icon: Smartphone, text: "App Control" },
    ],
    highlights: [
      "18× digital zoom for detailed monitoring",
      "Starlight color night vision with F1.6 lens",
      "Built-in spotlights for vivid low-light imaging",
      "Maintenance-free solar power for off-grid locations",
      "Free Person/Pet/Vehicle detection",
      "Privacy mode & encrypted local storage",
    ],
    category: "Security Cameras",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 24,
  },
  {
    id: "tp-tapo-c460-kit",
    name: "TP-Link Tapo 4K 8MP Solar Security Camera Kit | C460",
    sku: "TP-TAPO-C460-KIT",
    manufacturerSku: "Tapo C460 KIT",
    price: 2548.79,
    image: "/lovable-uploads/tapo-c460-product.png",
    boxImage: "/lovable-uploads/tapo-c460-mounted.png",
    description: "The TP-Link Tapo C460 is a 4K 8MP solar-powered security camera kit designed for outdoor surveillance. It provides ultra-high-definition video and includes a solar panel and high-capacity battery for continuous, maintenance-free operation.",
    features: [
      { icon: Camera, text: "4K 8MP Video" },
      { icon: Sun, text: "Solar Panel" },
      { icon: Battery, text: "High-Capacity Battery" },
      { icon: Shield, text: "Motion Detection" },
      { icon: Volume2, text: "Two-Way Audio" },
      { icon: HardDrive, text: "Local/Cloud Storage" },
    ],
    highlights: [
      "Full-colour night vision day and night",
      "Intelligent motion detection for people, vehicles and pets",
      "Two-way audio communication",
      "Smart notifications to your device",
      "Local or cloud storage options",
      "Tapo app for remote viewing and control",
    ],
    category: "Security Cameras",
    brand: "TP-Link",
    warranty: "2 Year",
    inStock: true,
    rating: 4.5,
    reviewCount: 18,
  },
  {
    id: "gs-gwn7806pl-pro",
    name: "Grandstream Enterprise L2++ 48 Port Managed GbE PoE Switch 120W",
    sku: "GS-GWN7806PL-PRO",
    manufacturerSku: "GWN7806PL-PRO",
    price: 11878.35,
    image: "/lovable-uploads/gwn7806pl-pro-front.png",
    boxImage: "/lovable-uploads/gwn7806pl-pro-back.png",
    description: "Layer 2++ Managed Network switch with 48x Gigabit RJ45 PoE ports and 120W PoE budget. Enterprise-grade networking solution with advanced management features, VLAN support, and seamless integration with Grandstream's GWN Cloud management platform.",
    features: [
      { icon: Network, text: "48 GbE Ports" },
      { icon: Zap, text: "120W PoE Budget" },
      { icon: Server, text: "Layer 2++ Managed" },
      { icon: Shield, text: "Enterprise Security" },
      { icon: Cable, text: "SFP+ Uplinks" },
      { icon: Wifi, text: "Cloud Management" },
    ],
    highlights: [
      "48x Gigabit RJ45 PoE ports for high-density deployments",
      "120W total PoE power budget",
      "Layer 2++ switching with advanced VLAN support",
      "GWN Cloud management platform integration",
      "Enterprise-grade QoS and traffic management",
      "Rack-mountable 1U form factor",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.6,
    reviewCount: 8,
  },
  {
    id: "gs-gwn7806ph-pro",
    name: "Grandstream Enterprise L2++ 48 Port Managed GbE PoE Switch High-Power",
    sku: "GS-GWN7806PH-PRO",
    manufacturerSku: "GWN7806PH-PRO",
    price: 15742.35,
    image: "/lovable-uploads/gwn7806ph-pro-front.png",
    boxImage: "/lovable-uploads/gwn7806ph-pro-angle.png",
    description: "Layer 2++ Managed Network switch with 48x Gigabit RJ45 PoE ports. High-power enterprise-grade networking solution with advanced management features, VLAN support, and seamless integration with Grandstream's GWN Cloud management platform. Ideal for high-density PoE deployments.",
    features: [
      { icon: Network, text: "48 GbE Ports" },
      { icon: Zap, text: "High-Power PoE" },
      { icon: Server, text: "Layer 2++ Managed" },
      { icon: Shield, text: "Enterprise Security" },
      { icon: Cable, text: "SFP+ Uplinks" },
      { icon: Wifi, text: "Cloud Management" },
    ],
    highlights: [
      "48x Gigabit RJ45 PoE ports for high-density deployments",
      "High-power PoE budget for demanding devices",
      "Layer 2++ switching with advanced VLAN support",
      "GWN Cloud management platform integration",
      "Enterprise-grade QoS and traffic management",
      "Rack-mountable 1U form factor",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.7,
    reviewCount: 5,
  },
  {
    id: "gs-gwn7816p",
    name: "Grandstream Enterprise L3 48 Port Managed GbE PoE++ Switch 900W",
    sku: "GS-GWN7816P",
    manufacturerSku: "GWN7816P",
    price: 18480.29,
    image: "/lovable-uploads/gwn7816p-angle1.png",
    boxImage: "/lovable-uploads/gwn7816p-angle2.png",
    description: "High-capacity Layer 3 managed switch built for enterprise networks requiring advanced performance, scalability, and security. With 48 Gigabit Ethernet ports and 6 10-Gigabit SFP+ uplinks, it delivers robust connectivity for high-density deployments. PoE, PoE+, and PoE++ support with a 900W power budget ensures reliable power delivery to demanding devices.",
    features: [
      { icon: Network, text: "48 GbE + 6 SFP+" },
      { icon: Zap, text: "900W PoE++" },
      { icon: Server, text: "Layer 3 Managed" },
      { icon: Shield, text: "Advanced Security" },
      { icon: Cable, text: "10G Uplinks" },
      { icon: Wifi, text: "Stacking Support" },
    ],
    highlights: [
      "48× Gigabit Ethernet ports + 6× 10-Gigabit SFP+ uplinks",
      "900W PoE budget with PoE/PoE+/PoE++ and dynamic allocation",
      "Full IPv4 and IPv6 protocol support",
      "Stacking support for managing multiple switches",
      "ARP Inspection, IP Source Guard, DHCP snooping security",
      "Dual boot, link aggregation, and storm control",
    ],
    category: "Networking",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.8,
    reviewCount: 6,
  },
  {
    id: "gs-gwn7672",
    name: "Grandstream Enterprise WiFi 7 Indoor Access Point | GWN7672",
    sku: "GS-GWN7672",
    manufacturerSku: "GWN7672",
    price: 4214.41,
    image: "/lovable-uploads/gwn7672-front.png",
    boxImage: "/lovable-uploads/gwn7672-back.png",
    description: "Enterprise-grade Wi-Fi 7 access point designed for medium to high-density environments such as offices, schools, hotels, and large retail spaces. Supports ultra-high-speed wireless connectivity with up to 11Gbps aggregate throughput for demanding applications including HD video streaming, real-time collaboration, and VoIP.",
    features: [
      { icon: Wifi, text: "WiFi 7 BE11000" },
      { icon: Signal, text: "11Gbps Speed" },
      { icon: Users, text: "384 Clients" },
      { icon: Radio, text: "175m Range" },
      { icon: Shield, text: "Secure Boot" },
      { icon: Server, text: "Embedded Controller" },
    ],
    highlights: [
      "Up to 11Gbps aggregate wireless throughput (BE11000)",
      "5Gbps aggregate wired throughput",
      "2x2x2:2 MIMO with MLO, 4KQAM, MRU technology",
      "Coverage range up to 175 metres",
      "Supports up to 384 concurrent Wi-Fi clients",
      "Self-power adaptation with PoE+ auto-detection",
    ],
    category: "Wi-Fi",
    brand: "Grandstream",
    warranty: "3 Year",
    inStock: true,
    rating: 4.9,
    reviewCount: 15,
  },
];

export const getCategories = (): string[] => {
  return [...new Set(products.map(p => p.category))];
};

export const getBrands = (): string[] => {
  return [...new Set(products.map(p => p.brand))];
};
